apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-test
  namespace: demo
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-test
  namespace: demo
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: master
      image: kubernetes/redis:v1
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: redis-data
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-test
