# Source: storageos/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: storageos-api
  namespace: demo
  labels:
    app: storageos
type: "kubernetes.io/storageos"
data:
  # Address build from the ClusterIP of the storageos service. In the format $(echo -n "tcp://$ClusterIP:5705" | base64)
  apiAddress: "ADDRESS"
  apiUsername: "c3RvcmFnZW9z"
  apiPassword: "c3RvcmFnZW9z"
