# Source: storageos/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: storageos-api
  namespace: default # This has to be "default" for openshift
  labels:
    app: storageos
type: "kubernetes.io/storageos"
data:
  # apiAddress: "aHR0cDovL3N0b3JhZ2Vvczo1NzA1"
  apiAddress: "c3RvcmFnZW9zOjU3MDU="
  apiUsername: "c3RvcmFnZW9z"
  apiPassword: "c3RvcmFnZW9z"
